#!/bin/bash
set -euo pipefail

# Update README.md with tool catalogue from library folder structure
# Groups by category, lists tools alphabetically with author info
# Matches the profile format: tool ID + author

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

README_FILE="README.md"
TEMP_FILE="${README_FILE}.tmp"
CATALOGUE_MARKER="<!-- AUTO-GENERATED CATALOGUE -->"

# Function to scan library and collect all tools by category
collect_tools() {
    local category=$1
    
    for scope in "shared" "xapids" "tihany7"; do
        local path="library/${scope}/${category}"
        if [[ ! -d "$path" ]]; then
            continue
        fi

        if [[ "$category" == "skills" ]]; then
            # Skills are stored as:
            #   library/{author}/skills/{skill-id}/SKILL.md
            find "$path" -type f -name 'SKILL.md' ! -path '*/.*' ! -path '*/_*' ! -name '.gitkeep' | while read -r file; do
                local id
                id=$(basename "$(dirname "$file")")
                local relpath="${file#./}"

                # Output as: tool_id|author|filepath
                echo "${id}|${scope}|${relpath}"
            done
        else
            # Find all files (excluding .gitkeep, hidden files, and _private docs)
            find "$path" -type f ! -name '.*' ! -name '.gitkeep' ! -name '_*' | while read -r file; do
                local basename=$(basename "$file")
                local id="${basename%.*}"
                local relpath="${file#./}"
                
                # Output as: tool_id|author|filepath
                echo "${id}|${scope}|${relpath}"
            done
        fi
    done | sort -t'|' -k1,1
}

# Helper to capitalize first letter
capitalize() {
    echo "$(echo "${1:0:1}" | tr '[:lower:]' '[:upper:]')${1:1}"
}

# Extract everything before the catalogue marker (or whole file if no marker)
if grep -q "$CATALOGUE_MARKER" "$README_FILE"; then
    sed "/$CATALOGUE_MARKER/q" "$README_FILE" > "$TEMP_FILE"
else
    # No marker exists, add it at the end
    cat "$README_FILE" > "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
    echo "$CATALOGUE_MARKER" >> "$TEMP_FILE"
fi

# Build catalogue section
cat >> "$TEMP_FILE" << 'EOF'

## Available Tools

Auto-generated list of all tools in the library. Your profile is automatically updated with these tools.

EOF

# Process all categories in order
CATEGORIES=("agents" "skills" "commands" "mcp" "cli")

for category in "${CATEGORIES[@]}"; do
    cat_title=$(capitalize "$category")
    echo "" >> "$TEMP_FILE"
    echo "### ${cat_title}" >> "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
    
    # Collect all tools for this category
    tools=$(collect_tools "$category")
    
    if [[ -n "$tools" ]]; then
        while IFS='|' read -r tool_id author filepath; do
            echo "- **${tool_id}** - author: ${author}" >> "$TEMP_FILE"
        done <<< "$tools"
    else
        echo "*No items yet*" >> "$TEMP_FILE"
    fi
    
    echo "" >> "$TEMP_FILE"
done

# Add footer
cat >> "$TEMP_FILE" << EOF

---

*Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC") • Auto-generated by \`scripts/gen-catalogue.sh\`*
EOF

# Replace README
mv "$TEMP_FILE" "$README_FILE"

echo "✓ README.md updated with tool catalogue"
